global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'train-api'
    static_configs:
      - targets: ['train-api:5002']

  - job_name: 'predict-api'
    static_configs:
      - targets: ['predict-api:5003']

  - job_name: 'gate-api'
    static_configs:
      - targets: ['gate-api:5000']

  - job_name: 'minilm-encoder'
    static_configs:
      - targets: ['minilm-encoder:5004']

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']
