[pytest]
# Root directory for tests
testpaths = tests

# Python path to include project root (so imports like train_api.services work)
pythonpath = .

# Markers for categorizing tests
markers =
    integration: mark a test as an integration test
    unit: mark a test as a unit test

# Verbose output
addopts = -v --disable-warnings

# Optional: fail fast on first failure
# addopts = -v --disable-warnings -x
filterwarnings =
    #ignore:.*invalid image filename.*:UserWarning
    #ignore:.*PyDataset.*super\(\).__init__.*:UserWarning
    ignore:Found .* invalid image filename.*:UserWarning
    ignore:Your `PyDataset` class should call `super\(\).__init__\(\*\*kwargs\)`:UserWarning